version: "2.2"
services:
  backend-container:
    build: .
    volumes:
      - ./classifica:/var/www/html
    ports:
      - 8080:80
  db-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD= ciccio
    volumes:
      - ./dati-mysql:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1